### ISSUE TITLE
[FEATURE] implement unit testing 

### ISSUE THREAD

**Issue by chrisobi02** [yimbymelbourne/council-meeting-agenda-scraper#34]
Currently all webscraper changes and implementations require manual testing to ensure they are functioning as desired. 

**Implementation**
Implementing unit testing on all scrapers and integrating it into an automated ci/cd pipeline would allow for faster development of new scrapers.

**Comment by ArchangelEkim** [comment]
What testing framework should we use? Pytest seems to be the suggested choice based on its beginners' ease of use and a wide array of functionality and descriptiveness.

**Comment by ArchangelEkim** [comment]
I am currently trying out pytest as a framework for testing dates and links as mentioned in #14

**Comment by chrisobi02** [comment]
Hey Michael,
My experience is with pytest - with parameterised tests we should basically
be able to knock all the tests out in one function. Have you set up the
actions pipeline yet? If not, the branch associated with the issue should
have a (prototype) one ready to go. I haven't been able to do more as I
haven't had access to a computer.

**Comment by ArchangelEkim** [comment]
Yes, I tried out pytest today and got 2 parameterised test functions working. I would work on the branch here then since you have set up a workflow.

**Comment by ArchangelEkim** [comment]
Also in general Ive finally learnt a bit more about working with github and branching vs forking so Ill be abandoning my fork eventually and just work on branches.

**Comment by ArchangelEkim** [comment]
I just don't have permission to push to the branch yet tho...

**Comment by chrisobi02** [comment]
Weird - I have no idea why that would be the case

**Comment by ArchangelEkim** [comment]
Im not sure either. @jonobri?

**Comment by jonobri** [comment]
@ArchangelEkim I think I have resolved this, but can't be 100% sure.

**Comment by ArchangelEkim** [comment]
Yep, that seems to have fixed it ☺️

**Comment by ArchangelEkim** [comment]
Just pushed my first 2 testing functions to branch #34. Will continue to test more but currently they do work basically.

**Comment by chrisobi02** [comment]
This is big news - what do you think about the relative imports? I'm kinda
interested in restructuring to make it possible to just import from
scrapers without needing the dynamic stuff.

**Comment by ArchangelEkim** [comment]
I'm not sure, the dynamic imports copied from elsewhere allow for minimal code and will dynamically scale. Plus when in vscode with pytest framework setup, I can test for each scraper for each function or do them as a group. I don't know how this will work for the workflow so it may need to be setup differently.

**Comment by jonobri** [comment]
@chrisobi02 @ArchangelEkim I've added you both as maintainers of this repo, so once you're happy with testing regimen you will be able to merge accordingly.
