### ISSUE TITLE
[FEATURE] Logging

### ISSUE THREAD

**Issue by jonobri** [yimbymelbourne/council-meeting-agenda-scraper#5]
**Is your feature request related to a problem? Please describe.**
Ensure clear logs are produced on output, which tell us about each scrapers' output and progress. 

**Describe the solution you'd like**
Logger produces easily parseable .txt files with all relevant info

**Describe alternatives you've considered**
N/A

**Additional context**
Should log all errors and outputs.

**Comment by catatonicChimp** [comment]
This should be reopened, using print and piping the output isn't really a good solution
I've implemented logger into #23, it still needs some love in some of the scrapers to replace print statements with logger but it does a good job of logging to terminal and to log files.

**Comment by jonobri** [comment]
Agreed! It is in fact a bad solution! 

Will go through #23 today.
