### ISSUE TITLE
[New Scraper] NSW: Strathfield

### ISSUE THREAD

**Issue by ArchangelEkim** [yimbymelbourne/council-meeting-agenda-scraper#56]
**Council Name:**
Strathfield Council

**Link to agenda webpage:**
https://www.strathfield.nsw.gov.au/council/council-meetings/

**Webpage quirks**
Grouped by year first through link then the usual accordion style from January down to December

**Additional context**
E.g.
![image](https://github.com/yimbymelbourne/council-meeting-agenda-scraper/assets/42601907/ec7fa160-f702-434d-a806-6431f92739a7)

**Comment by AKST** [comment]
Wow, this one look like a PITA to crawl, lol
