### ISSUE TITLE
[New Scraper] VIC: Manningham

### ISSUE THREAD

**Issue by ArchangelEkim** [yimbymelbourne/council-meeting-agenda-scraper#64]
**Council Name:**
Manningham Council

**Link to agenda webpage:**
https://www.manningham.vic.gov.au/about-council/how-council-works/council-meetings

**Webpage quirks**
It's odd; it uses teaser blocks in a 3-month group. Which then have to be clicked on to access files.

**Additional context**
![image](https://github.com/yimbymelbourne/council-meeting-agenda-scraper/assets/42601907/93cb4b87-35f4-46c8-b062-e832413eae9f)

**Comment by ryanward-io** [comment]
Happy to do this one - seems simple
